name=input("enter name:")
branch=input("enter branch:")
gender=input("enter gender:")
college=input("enter nameclg:")
age=int(input("enter age:"))
print("name:",name)
print("branch:",branch)
print("gender:",gender)
print("clg:",college)
print("age:",age)